version: 2.1

orbs:
  sfdx: circleci/salesforce-sfdx@2.2.0

workflows:
  version: 2
  all_tasks:
    jobs:
      - formatting
      - build-bridge
      - unit-test:
          context: apex-sdk-ci

jobs:
  formatting:
    docker:
      - image: cimg/openjdk:17.0-node
    steps:
        - checkout
        - run:
            name: Install Prettier
            command: npm ci
        - run:
            name: Check Formatting
            command: |
             npm run prettier:check:ci

  build-bridge:
    docker:
      - image: cimg/go:1.15
    steps:
      - checkout
      - run:
          name: Build
          command: |
            cd bridge
            go build .

  unit-test:
    executor: sfdx/default
    steps:
      - checkout
      - sfdx/install:
          version: "latest"
      - sfdx/auth:
          defaultusername: ${DEFAULT_USERNAME}
      - sfdx/scratch-create:
          scratch-alias: circleci
          scratch-config: ./config/project-scratch-def.json
      - sfdx/scratch-open:
          scratch-alias: circleci
      - run: sfdx force:source:push -u circleci
      - run: sfdx force:apex:test:run --synchronous -u circleci
      - sfdx/scratch-delete:
          scratch-alias: circleci
