name: Run CI
on:
  push:
    branches: [ main, 'feat/**' ]
    paths-ignore:
      - '**.md' # Do not need to run CI for markdown changes.
  pull_request:
    branches: [ main, 'feat/**' ]
    paths-ignore:
      - '**.md'

jobs:
  build-apex:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed if using OIDC to get release secrets.

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
      - name: Install Salesforce CLI (sfdx)
        run: npm install @salesforce/cli --global

      - name: Install packages
        run: npm ci

      - name: Check formatting
        run: npm run prettier:check:ci

      - uses: launchdarkly/gh-actions/actions/release-secrets@release-secrets-v1.2.0
        name: 'Get secrets from AWS SSM'
        with:
          aws_assume_role: ${{ vars.AWS_ROLE_ARN }}
          ssm_parameter_pairs: '
            /production/common/releasing/apex/username = DEFAULT_USERNAME,
            /production/common/releasing/apex/consumer_key = SFDX_CONSUMER_KEY,
            /production/common/releasing/apex/jwt_key = SFDX_JWT_KEY,
            /production/common/releasing/apex/server.key = SERVER_KEY'

      - name: Create server.key
        run: echo -n "$SERVER_KEY" > server.key

      - name: Authorize scratch organization
        run: |
          sf org login jwt \
            --username $DEFAULT_USERNAME \
            --client-id $SFDX_CONSUMER_KEY \
            --jwt-key-file server.key \
            --set-default \
            --alias target

      - name: Create scratch organization
        run: |
          sf org create scratch \
            --definition-file ./config/project-scratch-def.json \
            --alias github \
            --set-default \
            --target-dev-hub target

      - name: Deploy SDK
        run: sf project deploy start --source-dir force-app

      - name: Trigger unit tests
        run: sf apex run test --synchronous --test-level=RunAllTestsInOrg

  build-bridge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go v1.15
        uses: actions/setup-go@v5
        with:
          go-version: "1.15"

      - name: Build
        run: |
          cd bridge
          go build .
